# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CarpeDM - Admin Portal

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2
   
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 3 - Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v1      
      with:
        chromedriver-version: '99.0.4844.51'

    - name: Step 4 - Have GitHub Actions Buid Maven Project
      run: mvn clean install
